### ISSUE TITLE
reorder the axes within the figure

### ISSUE THREAD

**Issue by mnky9800n** [sbebo/joypy#10]
Currently the axes are ordered from low to high from top to bottom respectively. Is there a way to reverse this order? Or specify a custom order?

if you reverse `data` on line 390:

`    for i, group in enumerate(data[::-1]):`

And reverse `labels` on line 444:

`            _setup_axis(a, global_x_range, col_name=labels[::-1][i], grid=ygrid)`

It will reverse the order. But this seems a bit hacky, maybe there is a better way to do it?

**Comment by leotac** [comment]
I think the easiest way would be to edit the input data so that they will be displayed in the order you want, rather than adding an option/changing the code.

How you do it would depend on the kind of object you are passing -- for a (non-grouped) dataframe, the order is given by the order of the columns, so you would need to reorder the columns as you like:

```python
fig, axes = joypy.joyplot(iris)
```
![iris_before](https://user-images.githubusercontent.com/1311290/34479444-3d859888-efa7-11e7-8d12-e5f20ea11531.png)

```python
rev = iris[iris.columns[::-1]]
fig, axes = joypy.joyplot(rev)
```
![iris_after](https://user-images.githubusercontent.com/1311290/34479443-3d55ac2c-efa7-11e7-8384-211aec4d20c0.png)

For grouped dataframes, rather than using the `by` argument):

```python
fig, axes = joypy.joyplot(iris, by="Name")
```
![iris_grouped_before](https://user-images.githubusercontent.com/1311290/34479513-a6db4df0-efa7-11e7-8439-223a74d01400.png)

the simplest way is to pass a grouped dataframe with the groups in the desired order. This can be done by first reordering the values in the dataframe, and then grouping with `sort=False`:

```python
ordered = iris.sort_values("Name", ascending=False)
grouped = ordered.groupby("Name", sort=False)
fig, axes = joypy.joyplot(grouped)
```
![iris_grouped_after](https://user-images.githubusercontent.com/1311290/34479512-a6678578-efa7-11e7-80d3-79193a281425.png)
