### ISSUE TITLE
It should be possible to sort the plots

### ISSUE THREAD

**Issue by EtienneT** [sbebo/joypy#40]
Lets say you do something like this:

`fig, axes = joypy.joyplot(df, by="company", column="Score")`

This will produce multiple graphs, sorted by the column "company".  "company" would be sorted alphabetically by default, but what if I want a custom sort of how the graph are shown?

For example to have something like this:
![MXT8U](https://user-images.githubusercontent.com/265924/63379910-506cd880-c363-11e9-9bce-195255b84581.png)

**Comment by leotac** [comment]
Hi, you can do it in a couple of different ways.

One way is to pass a DataFrameGroupBy object, using sort=False, like this:

```python
grouped = df.groupby("company", sort=False)
fig, axes = joypy.joyplot(grouped, column="Score")
```
in this case, the order of the original dataframe will be preserved after the grouping. So it's enough to arrange the original dataframe in the order you'd like to obtain after the grouping.

Another way is to avoid using a dataframe and pass a list or a dictionary (see notebook with the examples, "plotting with raw data"). In this case you can collect the values and just pass the structure as it is (the order will be preserved for dicts in python 3.7+, otherwise you can use a list).
As an example:
```python
d = {"C": c, "A": a, "B": b}
fig, ax = joypy.joyplot(d)
```

![exampl](https://user-images.githubusercontent.com/1311290/64491210-f70f0f80-d265-11e9-9baf-1ed6fb6c1bf9.png)
